version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_2407Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: TPP_services_in_FCS
  version: "1.0"
  gitServerName: kvv
  gitUrl: https://github.com/Karthik-V-IBM-10
  gitUsername: Karthik-V-IBM-10
  gitBranch: main
services:
- serviceName: project.siqa_git_2407.integrations:Call_refData
  packages:
  - name: SIQA_GIT_2407Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
- serviceName: project.siqa_git_2407.referencedata:refData
  packages:
  - name: SIQA_GIT_2407Project
    version: "1.0"
  - name: TPP_services_in_FCS
    version: "1.0"
